# Generated by Django 5.2.3 on 2026-07-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('rank', models.CharField(choices=[('instructor', 'مربی'), ('assistant', 'استادیار'), ('associate', 'دانشیار'), ('professor', 'استاد تمام'), ('emeritus', 'استاد بازنشسته')], max_length=20, verbose_name='مرتبه علمی')),
                ('status', models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'نیمه وقت'), ('visiting', 'مهمان')], default='full_time', max_length=20, verbose_name='وضعیت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professors/', verbose_name='عکس')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='اتاق')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('education', models.TextField(blank=True, verbose_name='سوابق تحصیلی')),
                ('specialization', models.TextField(blank=True, verbose_name='تخصص')),
                ('research_interests', models.TextField(blank=True, verbose_name='زمینه تحقیقاتی')),
                ('office_hours', models.TextField(blank=True, verbose_name='ساعت حضور')),
                ('personal_website', models.URLField(blank=True)),
                ('google_scholar', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('researchgate', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='academics.department', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
                'ordering': ['order', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان')),
                ('pub_type', models.CharField(choices=[('article', 'مقاله'), ('book', 'کتاب'), ('thesis', 'پایان\u200cنامه'), ('conference', 'کنفرانس'), ('report', 'گزارش')], default='article', max_length=20, verbose_name='نوع')),
                ('journal_conference', models.CharField(blank=True, max_length=300, verbose_name='مجله/کنفرانس')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True, verbose_name='چکیده')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='faculty.professor', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'انتشار',
                'verbose_name_plural': 'انتشارات',
                'ordering': ['-year'],
            },
        ),
    ]
