# Generated by Django 5.2.3 on 2026-08-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='چهار استاد نخست از میان همین\u200cها در بخش «هیئت علمی برگزیده» می\u200cآیند.', verbose_name='نمایش در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
