# Generated by Django 5.2.3 on 2026-08-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0007_alter_academiccalendar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('staff', 'کارکنان و مسئولان'), ('founder', 'هیات موسس'), ('trustee', 'هیات امنا'), ('faculty', 'اعضای هیات علمی'), ('group_head', 'مدیران گروه آموزشی'), ('lecturer', 'مدرسین')], db_index=True, max_length=20, verbose_name='دسته')),
                ('honorific', models.CharField(blank=True, help_text='مثلاً: دکتر، مهندس، حجت\u200cالاسلام', max_length=40, verbose_name='پیشوند')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('full_name', models.CharField(help_text='اگر خالی بماند از نام و نام خانوادگی ساخته می\u200cشود.', max_length=200, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(blank=True, max_length=300, verbose_name='سمت')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='رشته تحصیلی')),
                ('degree', models.CharField(blank=True, choices=[('phd', 'دکتری تخصصی'), ('ms', 'کارشناسی ارشد'), ('bs', 'کارشناسی'), ('other', 'سایر')], max_length=20, verbose_name='مدرک تحصیلی')),
                ('extension', models.CharField(blank=True, help_text='فقط عدد داخلی، مثلاً ۱۱۵', max_length=20, verbose_name='شماره داخلی')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن مستقیم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='directory/people/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد موسسه',
                'ordering': ['category', 'order', 'last_name', 'full_name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='directory_d_categor_9bddd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'full_name'), name='directory_person_unique_per_category')],
            },
        ),
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='نشانی')),
                ('category', models.CharField(choices=[('database', 'پایگاه داده و منابع لاتین'), ('journal', 'نشریات'), ('thesis', 'پایان\u200cنامه\u200cها'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('icon', models.CharField(blank=True, default='fas fa-database', max_length=60, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'منبع بیرونی',
                'verbose_name_plural': 'منابع و پایگاه\u200cهای بیرونی',
                'ordering': ['category', 'order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('url',), name='directory_resource_unique_url')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان رشته')),
                ('level', models.CharField(choices=[('associate_cont', 'کاردانی پیوسته'), ('associate_disc', 'کاردانی ناپیوسته'), ('bachelor_cont', 'کارشناسی پیوسته'), ('bachelor_disc', 'کارشناسی ناپیوسته'), ('master', 'کارشناسی ارشد'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='مقطع')),
                ('file', models.FileField(upload_to='curricula/', verbose_name='فایل PDF')),
                ('file_size', models.PositiveIntegerField(default=0, editable=False, verbose_name='حجم (بایت)')),
                ('approved_on', models.CharField(blank=True, help_text='همان\u200cطور که روی سند آمده، مثلاً ۱۴۰۰/۱۰/۱۵', max_length=30, verbose_name='تاریخ تصویب')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='توضیح')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد دانلود')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('major', models.ForeignKey(blank=True, help_text='اختیاری — برای پیوند دادن به صفحهٔ رشته', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_documents', to='academics.major', verbose_name='رشته مرتبط')),
            ],
            options={
                'verbose_name': 'سرفصل مصوب',
                'verbose_name_plural': 'سرفصل\u200cهای مصوب رشته\u200cها',
                'ordering': ['level', 'order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('level', 'title'), name='directory_curriculum_unique_per_level')],
            },
        ),
    ]
