# Generated by Django 5.2.3 on 2026-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_academiccalendar_options_and_more'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curriculumdocument',
            name='directory_curriculum_unique_per_level',
        ),
        migrations.AddConstraint(
            model_name='curriculumdocument',
            constraint=models.UniqueConstraint(fields=('level', 'title', 'approved_on'), name='directory_curriculum_unique_per_level'),
        ),
    ]
