# Generated by Django 5.2.3 on 2026-09-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_remove_curriculumdocument_directory_curriculum_unique_per_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryperson',
            name='academic_rank',
            field=models.CharField(blank=True, choices=[('instructor', 'مربی'), ('assistant', 'استادیار'), ('associate', 'دانشیار'), ('professor', 'استاد تمام'), ('emeritus', 'استاد بازنشسته')], help_text='اگر خالی بماند از مدرک تحصیلی حدس زده می\u200cشود (دکتری → استادیار). برای دانشیار و استاد تمام حتماً پرش کنید.', max_length=20, verbose_name='مرتبه علمی'),
        ),
    ]
