# Generated by Django 5.2.3 on 2026-07-09 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('target', models.CharField(choices=[('all', 'همه'), ('students', 'دانشجویان'), ('professors', 'اساتید'), ('staff', 'کارمندان')], default='all', max_length=20, verbose_name='مخاطب')),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='فایل پیوست')),
                ('is_active', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('professor', 'استاد'), ('staff', 'کارمند'), ('admin', 'مدیر')], default='student', max_length=20, verbose_name='نقش')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='عکس پروفایل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('student_id', models.CharField(blank=True, max_length=50, verbose_name='شماره دانشجویی/کارمندی')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='دانشکده/واحد')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
    ]
