# Generated by Django 5.2.3 on 2026-07-21 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_major_group_and_degree_types'),
        ('accounts', '0002_alter_userprofile_role_otpcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.major', verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='انقضا'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
