# Generated by Django 5.2.3 on 2026-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_identity_residence_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_status',
            field=models.CharField(choices=[('applicant', 'متقاضی'), ('active', 'در حال تحصیل'), ('leave', 'مرخصی'), ('withdrawn', 'انصراف'), ('expelled', 'اخراج'), ('graduated', 'فارغ\u200cالتحصیل')], db_index=True, default='active', max_length=20, verbose_name='وضعیت تحصیلی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تغییر وضعیت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='یادداشت وضعیت'),
        ),
    ]
