# Generated by Django 5.2.3 on 2026-07-29 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_canonical_degrees'),
        ('accounts', '0005_academic_status_clearance_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='وضعیت تأهل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quota',
            field=models.CharField(blank=True, default='', help_text='از پروندهٔ پذیرش منتقل می\u200cشود؛ مبنای تخفیف شهریه', max_length=20, verbose_name='سهمیه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('national_id',), name='uniq_profile_national_id'),
        ),
    ]
