# Generated by Django 5.2.3 on 2026-07-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_marital_status_userprofile_quota_and_more'),
        ('dashboard', '0007_classsession_enrollment_exam_seat_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entry_semester',
            field=models.ForeignKey(blank=True, help_text='مبنای محاسبه سنوات تحصیلی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_students', to='dashboard.semester', verbose_name='ترم ورود'),
        ),
    ]
