# Generated by Django 5.2.3 on 2026-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_entry_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.CharField(blank=True, help_text='با کلیک روی این اطلاعیه، بازدیدکننده به همین نشانی می\u200cرود — مثلاً \u200e/dashboard/registration/\u200e برای انتخاب واحد. خالی بگذارید تا اطلاعیه فقط متن باشد.', max_length=300, verbose_name='نشانی مقصد'),
        ),
    ]
