# Generated by Django 5.2.3 on 2026-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_announcement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.CharField(blank=True, help_text='اختیاری. اگر این اطلاعیه به صفحهٔ دیگری از سایت اشاره دارد — مثلاً \u200e/dashboard/registration/\u200e برای انتخاب واحد — همین\u200cجا بنویسیدش. خالی که بماند، کلیک روی اطلاعیه صفحهٔ خودِ همین اطلاعیه را باز می\u200cکند.', max_length=300, verbose_name='نشانی مقصد'),
        ),
    ]
