# Generated by Django 5.2.3 on 2026-07-17 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ترم')),
                ('semester_type', models.CharField(choices=[('fall', 'پاییز'), ('spring', 'بهار'), ('summer', 'تابستان')], max_length=20, verbose_name='نوع ترم')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سال تحصیلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('registration_open', models.BooleanField(default=False, verbose_name='ثبت\u200cنام باز')),
            ],
            options={
                'verbose_name': 'ترم',
                'verbose_name_plural': 'ترم\u200cها',
                'ordering': ['-academic_year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('assignment_type', models.CharField(choices=[('homework', 'تکلیف'), ('project', 'پروژه'), ('quiz', 'کوییز'), ('presentation', 'ارائه')], max_length=20, verbose_name='نوع')),
                ('due_date', models.DateTimeField(verbose_name='مهلت تحویل')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='امتیاز کل')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.course', verbose_name='درس')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='استاد')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.semester', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'ثبت\u200cنام شده'), ('in_progress', 'در حال گذراندن'), ('completed', 'تکمیل شده'), ('dropped', 'حذف شده'), ('failed', 'مردود')], default='registered', max_length=20, verbose_name='وضعیت')),
                ('mid_term_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره میان\u200cترم')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره نهایی')),
                ('attendance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره حضور')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course', verbose_name='درس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dashboard.semester', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام درس',
                'verbose_name_plural': 'ثبت\u200cنام دروس',
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tuition', 'شهریه'), ('dorm', 'خوابگاه'), ('book', 'کتاب'), ('exam', 'امتحان'), ('other', 'سایر')], max_length=20, verbose_name='نوع پرداخت')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه تراکنش')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.semester', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('midterm', 'میان\u200cترم'), ('final', 'پایان\u200cترم'), ('makeup', 'امتحان جایگزین'), ('practical', 'امتحان عملی')], max_length=20, verbose_name='نوع امتحان')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('location', models.CharField(max_length=100, verbose_name='مکان')),
                ('instructions', models.TextField(blank=True, verbose_name='دستورالعمل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.course', verbose_name='درس')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='dashboard.semester', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'برنامه امتحان',
                'verbose_name_plural': 'برنامه امتحانات',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('certificate', 'گواهی'), ('transcript', 'کارنامه'), ('recommendation', 'معرفی\u200cنامه'), ('leave', 'مرخصی'), ('extension', 'تمدید'), ('complaint', 'شکایت'), ('other', 'سایر')], max_length=20, verbose_name='نوع درخواست')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('processing', 'در حال بررسی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('response', models.TextField(blank=True, verbose_name='پاسخ')),
                ('file', models.FileField(blank=True, null=True, upload_to='requests/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'درخواست دانشجویی',
                'verbose_name_plural': 'درخواست\u200cهای دانشجویی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/', verbose_name='فایل')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره')),
                ('feedback', models.TextField(blank=True, verbose_name='بازخورد')),
                ('status', models.CharField(choices=[('submitted', 'تحویل داده شده'), ('graded', 'نمره داده شده'), ('late', 'تاخیری'), ('rejected', 'رد شده')], default='submitted', max_length=20, verbose_name='وضعیت')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dashboard.assignment', verbose_name='تکلیف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'تحویل تکلیف',
                'verbose_name_plural': 'تحویل تکالیف',
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'تاخیر'), ('excused', 'مرخصی')], default='present', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='dashboard.enrollment', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'unique_together': {('enrollment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.TextField(blank=True, verbose_name='برنامه کلاس')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='کلاس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.course', verbose_name='درس')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department', verbose_name='دانشکده')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='استاد')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='dashboard.semester', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'تخصیص تدریس',
                'verbose_name_plural': 'تخصیص\u200cهای تدریس',
                'unique_together': {('professor', 'course', 'semester')},
            },
        ),
    ]
