# Generated by Django 5.2.3 on 2026-07-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت سامانه آموزشی', 'verbose_name_plural': 'پرداخت\u200cهای سامانه آموزشی'},
        ),
    ]
