# Generated by Django 5.2.3 on 2026-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_payment_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='کد authority درگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='درگاه'),
        ),
    ]
