# Generated by Django 5.2.3 on 2026-07-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tuition_plan_discounts_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل\u200cشده')], default='open', max_length=20, verbose_name='وضعیت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clearance', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'تسویه پایان\u200cتحصیل',
                'verbose_name_plural': 'تسویه\u200cهای پایان\u200cتحصیل',
            },
        ),
        migrations.CreateModel(
            name='StudentLifecycleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('graduation', 'فارغ\u200cالتحصیلی'), ('withdrawal', 'انصراف از تحصیل'), ('leave', 'مرخصی تحصیلی')], max_length=20, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال\u200cشده'), ('under_review', 'در حال بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل / توضیحات')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lifecycle/', verbose_name='پیوست')),
                ('admin_response', models.TextField(blank=True, verbose_name='پاسخ ادمین')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lifecycle_requests', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'درخواست پایان مسیر تحصیلی',
                'verbose_name_plural': 'درخواست\u200cهای پایان مسیر تحصیلی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentClearanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('library', 'کتابخانه'), ('finance', 'مالی / شهریه'), ('education', 'آموزش'), ('lab', 'آزمایشگاه'), ('security', 'حراست'), ('dorm', 'خوابگاه')], max_length=20, verbose_name='واحد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('cleared', 'تسویه'), ('waived', 'معاف')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.studentclearance', verbose_name='تسویه')),
            ],
            options={
                'verbose_name': 'مورد تسویه',
                'verbose_name_plural': 'موارد تسویه',
                'ordering': ['id'],
                'unique_together': {('clearance', 'department')},
            },
        ),
    ]
