# Generated by Django 5.2.3 on 2026-07-29 14:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course_coreq_courses_course_prereq_courses_and_more'),
        ('dashboard', '0006_academic_status_clearance_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
            ],
            options={
                'verbose_name': 'جلسه کلاس',
                'verbose_name_plural': 'جلسات کلاس',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_seat_no',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='شماره صندلی امتحان'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='retake_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retakes', to='dashboard.enrollment', verbose_name='تکرار درسِ'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='۰ یعنی بدون محدودیت. با پر شدن ظرفیت، انتخاب واحد بسته می\u200cشود.', verbose_name='ظرفیت کلاس'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='attendance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره حضور'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره نهایی'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='mid_term_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره میان\u200cترم'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='class_schedule',
            field=models.TextField(blank=True, verbose_name='برنامه کلاس (متن)'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('final_grade__isnull', True), models.Q(('final_grade__gte', 0), ('final_grade__lte', 20)), _connector='OR'), name='enrollment_final_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('mid_term_grade__isnull', True), models.Q(('mid_term_grade__gte', 0), ('mid_term_grade__lte', 20)), _connector='OR'), name='enrollment_midterm_grade_range'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='teaching_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.teachingassignment', verbose_name='کلاس'),
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('teaching_assignment', 'day', 'start_time')},
        ),
    ]
