# Generated by Django 5.2.3 on 2026-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_classsession_enrollment_exam_seat_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='request_type',
            field=models.CharField(choices=[('certificate', 'گواهی اشتغال به تحصیل'), ('transcript', 'کارنامه / ریز نمرات'), ('recommendation', 'معرفی\u200cنامه'), ('leave', 'مرخصی تحصیلی'), ('course_drop', 'حذف اضطراری تک\u200cدرس'), ('internship', 'معرفی برای کارآموزی'), ('military', 'معافیت تحصیلی / نظام وظیفه'), ('loan', 'وام دانشجویی'), ('equivalent_degree', 'مدرک معادل کاردانی'), ('academic_issue', 'بررسی مسائل آموزشی'), ('clearance', 'تسویه حساب'), ('extension', 'تمدید سنوات'), ('complaint', 'شکایت'), ('other', 'سایر')], max_length=20, verbose_name='نوع درخواست'),
        ),
    ]
