# Generated by Django 5.2.3 on 2026-09-20 14:46

import core.private_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_request_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to=core.private_media.private_upload_to('submissions'), verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=core.private_media.private_upload_to('tuition_receipts'), verbose_name='فیش / رسید آفلاین'),
        ),
        migrations.AlterField(
            model_name='studentdiscountclaim',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.private_media.private_upload_to('tuition_discounts'), verbose_name='مدرک پیوست'),
        ),
        migrations.AlterField(
            model_name='studentlifecyclerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.private_media.private_upload_to('lifecycle'), verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.private_media.private_upload_to('requests'), verbose_name='فایل'),
        ),
    ]
