# Generated by Django 5.2.3 on 2026-07-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('semester', models.CharField(choices=[('fall', 'پاییز'), ('spring', 'بهار'), ('summer', 'تابستان')], max_length=20, verbose_name='نیم\u200cسال')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سال تحصیلی')),
                ('is_important', models.BooleanField(default=False, verbose_name='مهم')),
            ],
            options={
                'verbose_name': 'تقویم آموزشی',
                'verbose_name_plural': 'تقویم آموزشی',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دانشکده')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('short_description', models.TextField(blank=True, verbose_name='معرفی کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='تصویر')),
                ('head', models.CharField(blank=True, max_length=200, verbose_name='رئیس دانشکده')),
                ('established_year', models.CharField(blank=True, max_length=10, verbose_name='سال تأسیس')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دانشکده',
                'verbose_name_plural': 'دانشکده\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام آزمایشگاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='labs/', verbose_name='تصویر')),
                ('supervisor', models.CharField(blank=True, max_length=200, verbose_name='مسئول')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل')),
                ('equipment', models.TextField(blank=True, verbose_name='تجهیزات')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='academics.department', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'آزمایشگاه',
                'verbose_name_plural': 'آزمایشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام رشته')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('degree', models.CharField(choices=[('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='مقطع تحصیلی')),
                ('description', models.TextField(blank=True, verbose_name='معرفی رشته')),
                ('job_market', models.TextField(blank=True, verbose_name='بازار کار')),
                ('objectives', models.TextField(blank=True, verbose_name='اهداف')),
                ('curriculum', models.TextField(blank=True, verbose_name='سرفصل دروس')),
                ('total_credits', models.PositiveIntegerField(default=0, verbose_name='تعداد کل واحد')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='ظرفیت')),
                ('admission_requirements', models.TextField(blank=True, verbose_name='شرایط پذیرش')),
                ('tuition_fee', models.CharField(blank=True, max_length=200, verbose_name='شهریه')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='academics.department', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته\u200cهای تحصیلی',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='کد درس')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='تعداد واحد')),
                ('course_type', models.CharField(choices=[('required', 'اجباری'), ('elective', 'اختیاری'), ('general', 'عمومی'), ('specialized', 'تخصصی')], default='required', max_length=20, verbose_name='نوع درس')),
                ('prerequisites', models.CharField(blank=True, max_length=300, verbose_name='پیش\u200cنیاز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('semester', models.PositiveIntegerField(default=1, verbose_name='ترم')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.major', verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['semester', 'name'],
            },
        ),
    ]
