# Generated by Django 5.2.3 on 2026-07-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام گروه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('head', models.CharField(blank=True, max_length=200, verbose_name='مدیر گروه')),
                ('head_photo', models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='تصویر مدیر گروه')),
                ('head_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مدیر گروه')),
                ('head_phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن مدیر گروه')),
                ('description', models.TextField(blank=True, verbose_name='معرفی گروه')),
                ('goals', models.TextField(blank=True, verbose_name='اهداف گروه')),
                ('facilities', models.TextField(blank=True, verbose_name='امکانات و تجهیزات')),
                ('research_areas', models.TextField(blank=True, verbose_name='حوزه\u200cهای پژوهشی')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن گروه')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل گروه')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل')),
                ('established_year', models.CharField(blank=True, max_length=10, verbose_name='سال تأسیس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.department', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'گروه آموزشی',
                'verbose_name_plural': 'گروه\u200cهای آموزشی',
                'ordering': ['department', 'order', 'name'],
            },
        ),
    ]
