# Generated by Django 5.2.3 on 2026-07-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['group', 'degree', 'order', 'name'], 'verbose_name': 'رشته تحصیلی', 'verbose_name_plural': 'رشته\u200cهای تحصیلی'},
        ),
        migrations.AddField(
            model_name='major',
            name='group',
            field=models.ForeignKey(blank=True, help_text='گروه آموزشی که این رشته زیر آن نمایش داده می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majors', to='academics.academicgroup', verbose_name='گروه آموزشی'),
        ),
        migrations.AddField(
            model_name='major',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='major',
            name='degree',
            field=models.CharField(choices=[('associate_cont', 'کاردانی پیوسته'), ('associate_disc', 'کاردانی ناپیوسته'), ('associate', 'کاردانی'), ('bachelor_cont', 'کارشناسی پیوسته'), ('bachelor_disc', 'کارشناسی ناپیوسته'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='مقطع تحصیلی'),
        ),
    ]
