# Generated by Django 5.2.3 on 2026-07-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_major_group_and_degree_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='curriculum_pdf',
            field=models.FileField(blank=True, help_text='برنامه درسی / سرفصل PDF این رشته', null=True, upload_to='majors/curriculum/', verbose_name='فایل سرفصل (PDF)'),
        ),
        migrations.AddField(
            model_name='major',
            name='curriculum_word',
            field=models.FileField(blank=True, help_text='نسخه Word سرفصل در صورت وجود', null=True, upload_to='majors/curriculum/word/', verbose_name='فایل سرفصل (Word)'),
        ),
    ]
