# Generated by Django 5.2.3 on 2026-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_canonical_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coreq_courses',
            field=models.ManyToManyField(blank=True, help_text='باید هم\u200cزمان یا پیش از این درس گرفته شده باشند.', related_name='is_coreq_for', to='academics.course', verbose_name='دروس هم\u200cنیاز'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereq_courses',
            field=models.ManyToManyField(blank=True, help_text='دانشجو تا این دروس را پاس نکند نمی\u200cتواند این درس را بردارد.', related_name='is_prereq_for', to='academics.course', verbose_name='دروس پیش\u200cنیاز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, help_text='فقط توضیح نمایشی. برای اعمال واقعی از «دروس پیش\u200cنیاز» استفاده کنید.', max_length=300, verbose_name='پیش\u200cنیاز (متن)'),
        ),
    ]
