# Generated by Django 5.2.3 on 2026-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course_coreq_courses_course_prereq_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccalendar',
            options={'ordering': ['order', 'start_date'], 'verbose_name': 'تقویم آموزشی', 'verbose_name_plural': 'تقویم آموزشی'},
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='action',
            field=models.CharField(blank=True, choices=[('', 'بدون لینک'), ('registration', 'انتخاب واحد'), ('schedule', 'برنامه کلاس'), ('payments', 'پرداخت شهریه'), ('exams', 'برنامه امتحانات'), ('exam_card', 'کارت ورود به جلسه'), ('grades', 'نمرات و کارنامه'), ('courses', 'دروس من'), ('clearance', 'تسویه حساب'), ('requests', 'درخواست\u200cهای دانشجویی'), ('admissions_apply', 'ثبت درخواست پذیرش'), ('admissions_track', 'پیگیری پذیرش'), ('tuition_calc', 'محاسبه شهریه'), ('external', 'لینک دلخواه (آدرس دستی)')], default='', help_text='صفحهٔ مرتبط در پنل دانشجو یا سایت.', max_length=30, verbose_name='کلیک روی این مرحله کاربر را ببرد به'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='external_url',
            field=models.CharField(blank=True, default='', help_text='فقط اگر گزینهٔ «لینک دلخواه» را انتخاب کرده\u200cاید.', max_length=300, verbose_name='آدرس دلخواه'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='کلاس Font Awesome، مثلاً fa-check-square. خالی = خودکار.', max_length=60, verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='image',
            field=models.ImageField(blank=True, help_text='اختیاری — پشت باکس این مرحله نمایش داده می\u200cشود.', null=True, upload_to='calendar/', verbose_name='تصویر مرحله'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش در تایم\u200cلاین'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='در صورت برابری، تاریخ شروع ملاک است.', verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='tone',
            field=models.CharField(choices=[('gold', 'طلایی (پیش\u200cفرض)'), ('teal', 'فیروزه\u200cای'), ('violet', 'بنفش'), ('rose', 'گلی'), ('amber', 'کهربایی'), ('sky', 'آبی آسمانی')], default='gold', max_length=10, verbose_name='رنگ باکس'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='description',
            field=models.TextField(blank=True, help_text='در باکس تایم\u200cلاین زیر عنوان نمایش داده می\u200cشود.', verbose_name='توضیحات'),
        ),
    ]
