# Generated by Django 5.2.3 on 2026-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_academiccalendar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='کد رسمی وزارت علوم — داوطلب در دفترچهٔ سنجش با همین کد رشته را پیدا می\u200cکند.', max_length=20, verbose_name='کد رشته'),
        ),
        migrations.AddField(
            model_name='major',
            name='internship_hours',
            field=models.PositiveIntegerField(default=0, help_text='صفر یعنی این رشته کارآموزی ندارد.', verbose_name='ساعت کارآموزی'),
        ),
    ]
