# Generated by Django 5.2.3 on 2026-08-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_major_code_major_internship_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='bg_color',
            field=models.CharField(blank=True, default='', help_text='هر رنگی که بخواهید، مثل #1f6f5c. خالی بگذارید تا همان «رنگ باکس» بالا استفاده شود. رنگ نوشته خودکار روشن یا تیره می\u200cشود تا خوانا بماند.', max_length=9, verbose_name='رنگ دلخواه زمینه'),
        ),
    ]
