# Generated by Django 5.2.3 on 2026-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_academiccalendar_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='graduate_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در همان زیرمنو؛ عدد کوچک\u200cتر بالاتر.', verbose_name='ترتیب در تحصیلات تکمیلی'),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='has_graduate',
            field=models.BooleanField(default=False, help_text='اگر تیک بخورد، زیر منوی «تحصیلات تکمیلی» می\u200cآید.', verbose_name='دارای تحصیلات تکمیلی'),
        ),
    ]
