# Generated by Django 5.2.3 on 2026-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_academicgroup_graduate_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_photo',
            field=models.ImageField(blank=True, null=True, upload_to='departments/heads/', verbose_name='عکس رئیس دانشکده'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_title',
            field=models.CharField(blank=True, help_text='مثلاً: دانشیار گروه مدیریت صنعتی', max_length=120, verbose_name='سمت رئیس دانشکده'),
        ),
    ]
