# Generated by Django 5.2.3 on 2026-08-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_department_head_photo_department_head_title'),
        ('faculty', '0002_professor_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='head_professor',
            field=models.ForeignKey(blank=True, help_text='با انتخاب استاد، نام و عکس و مرتبه و راه تماسش خودکار روی صفحهٔ گروه می\u200cآید. اگر مدیر گروه عضو هیئت علمی نیست، این را خالی بگذارید و فیلدهای زیر را دستی پر کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_groups', to='faculty.professor', verbose_name='مدیر گروه (از اعضای هیئت علمی)'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='head',
            field=models.CharField(blank=True, max_length=200, verbose_name='مدیر گروه (دستی)'),
        ),
    ]
