# Generated by Django 5.2.3 on 2026-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_academicgroup_head_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='head_honorific',
            field=models.CharField(blank=True, help_text='مثلاً «دکتر» یا «مهندس». پیش از نام مدیر می\u200cآید — چه نام از پروندهٔ هیئت علمی بیاید، چه دستی نوشته شده باشد.', max_length=40, verbose_name='پیشوند مدیر گروه'),
        ),
    ]
