# Generated by Django 5.2.3 on 2026-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_academicgroup_head_honorific'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='head_locked',
            field=models.BooleanField(default=False, help_text='با زدن این تیک، به\u200cروزرسانی خودکار به مدیر این گروه دست نمی\u200cزند. هر بار که از همین صفحه مدیر را عوض یا پاک کنید، خودکار زده می\u200cشود.', verbose_name='مدیر گروه دستی تنظیم شده'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='head',
            field=models.CharField(blank=True, help_text='اگر اینجا نامی بنویسید، همان روی صفحهٔ گروه می\u200cنشیند — حتی اگر استادی هم انتخاب شده باشد.', max_length=200, verbose_name='مدیر گروه (دستی)'),
        ),
    ]
