# Generated by Django 5.2.3 on 2026-09-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_academicgroup_head_locked_alter_academicgroup_head'),
        ('faculty', '0002_professor_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorific', models.CharField(blank=True, help_text='مثلاً «دکتر» یا «مهندس».', max_length=40, verbose_name='پیشوند')),
                ('name', models.CharField(blank=True, help_text='اگر استادی انتخاب نکرده\u200cاید، نام را اینجا بنویسید. اگر هر دو پر باشند، همین نوشته می\u200cنشیند.', max_length=200, verbose_name='نام (دستی)')),
                ('note', models.CharField(blank=True, help_text='مثلاً «ارشد» یا «کارشناسی». کنار نام می\u200cآید.', max_length=60, verbose_name='توضیح')),
                ('photo', models.ImageField(blank=True, help_text='اگر استاد انتخاب شده و عکس دارد، لازم نیست.', null=True, upload_to='groups/heads/', verbose_name='تصویر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_heads', to='academics.academicgroup', verbose_name='گروه آموزشی')),
                ('professor', models.ForeignKey(blank=True, help_text='با انتخاب استاد، نام و عکس و مرتبه و راه تماسش خودکار می\u200cآید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_head_roles', to='faculty.professor', verbose_name='از اعضای هیئت علمی')),
            ],
            options={
                'verbose_name': 'مدیر گروه',
                'verbose_name_plural': 'مدیران گروه',
                'ordering': ['group', 'order', 'id'],
            },
        ),
    ]
