# Generated by Django 5.2.3 on 2026-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_grouphead'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouphead',
            name='rank_override',
            field=models.CharField(blank=True, choices=[('instructor', 'مربی'), ('assistant', 'استادیار'), ('associate', 'دانشیار'), ('professor', 'استاد تمام'), ('emeritus', 'استاد بازنشسته')], help_text='خالی بگذارید تا از پروندهٔ هیئت علمی بیاید.', max_length=20, verbose_name='مرتبه علمی'),
        ),
    ]
