# Generated by Django 5.2.3 on 2026-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_grouphead_rank_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphead',
            name='rank_override',
            field=models.CharField(blank=True, choices=[('instructor', 'مربی'), ('assistant', 'استادیار'), ('associate', 'دانشیار'), ('professor', 'استاد تمام'), ('emeritus', 'استاد بازنشسته')], help_text='خالی بگذارید تا از پروندهٔ هیئت علمی بیاید. اگر پرش کنید و استادی هم انتخاب شده باشد، همین مرتبه در پروندهٔ خودِ استاد هم ثبت می\u200cشود تا دو صفحهٔ سایت دو چیز نگویند.', max_length=20, verbose_name='مرتبه علمی'),
        ),
    ]
