# Generated by Django 5.2.3 on 2026-07-09 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('category_type', models.CharField(choices=[('academic', 'آموزشی'), ('research', 'پژوهشی'), ('cultural', 'فرهنگی'), ('administrative', 'اداری'), ('competitions', 'مسابقات'), ('conferences', 'همایش\u200cها'), ('announcement', 'اطلاعیه')], default='academic', max_length=30, verbose_name='نوع')),
                ('icon', models.CharField(default='fas fa-newspaper', max_length=100, verbose_name='آیکون')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='رنگ')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], default='image', max_length=10, verbose_name='نوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='تصویر')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدئو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('news_type', models.CharField(choices=[('news', 'خبر'), ('announcement', 'اطلاعیه'), ('event', 'رویداد')], default='news', max_length=20, verbose_name='نوع')),
                ('summary', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='خبر برجسته')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشرشده')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_at'],
            },
        ),
    ]
