# Generated by Django 5.2.3 on 2026-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='سال فارغ\u200cالتحصیلی')),
                ('major', models.CharField(max_length=200, verbose_name='رشته')),
                ('degree', models.CharField(max_length=100, verbose_name='مقطع')),
                ('current_position', models.CharField(blank=True, max_length=300, verbose_name='سمت فعلی')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='شرکت/سازمان')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/')),
                ('linkedin', models.URLField(blank=True)),
                ('success_story', models.TextField(blank=True, verbose_name='داستان موفقیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='برجسته')),
            ],
            options={
                'verbose_name': 'فارغ\u200cالتحصیل',
                'verbose_name_plural': 'فارغ\u200cالتحصیلان',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('subject', models.CharField(choices=[('general', 'عمومی'), ('academic', 'آموزشی'), ('admission', 'پذیرش'), ('financial', 'مالی'), ('technical', 'فنی'), ('complaint', 'شکایت'), ('suggestion', 'پیشنهاد')], default='general', max_length=20, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('reply', models.TextField(blank=True, verbose_name='پاسخ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
