# Generated by Django 5.2.3 on 2026-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general', 'عمومی'), ('academic', 'آموزشی'), ('admission', 'پذیرش'), ('financial', 'مالی'), ('technical', 'فنی'), ('complaint', 'شکایت'), ('suggestion', 'پیشنهاد'), ('presidency', 'ارتباط با ریاست')], default='general', max_length=20, verbose_name='موضوع'),
        ),
    ]
