# Generated by Django 5.2.3 on 2026-09-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_aab_parity_bank_docs_presidency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attachment',
            field=models.ImageField(blank=True, help_text='فیش واریزی یا هر تصویر پیوست دیگر.', null=True, upload_to='contact/receipts/%Y/%m/', verbose_name='تصویر پیوست'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general', 'عمومی'), ('academic', 'آموزشی'), ('admission', 'پذیرش'), ('financial', 'مالی'), ('technical', 'فنی'), ('complaint', 'شکایت'), ('suggestion', 'پیشنهاد'), ('presidency', 'ارتباط با ریاست'), ('tuition_receipt', 'ارسال فیش واریزی شهریه')], default='general', max_length=20, verbose_name='موضوع'),
        ),
    ]
