# Generated by Django 5.2.3 on 2026-09-20 14:46

import core.private_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactmessage_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='attachment',
            field=models.ImageField(blank=True, help_text='فیش واریزی یا هر تصویر پیوست دیگر.', null=True, upload_to=core.private_media.private_upload_to('contact/receipts'), verbose_name='تصویر پیوست'),
        ),
    ]
