# Generated by Django 5.2.3 on 2026-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان همایش')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=200, verbose_name='برگزارکننده')),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='conferences/')),
                ('is_upcoming', models.BooleanField(default=True, verbose_name='آینده')),
            ],
            options={
                'verbose_name': 'همایش',
                'verbose_name_plural': 'همایش\u200cها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IndustryPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('partnership_type', models.CharField(blank=True, max_length=200, verbose_name='نوع همکاری')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'همکاری صنعتی',
                'verbose_name_plural': 'همکاری\u200cهای صنعتی',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مجله')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
                ('website', models.URLField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='journals/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'مجله علمی',
                'verbose_name_plural': 'مجلات علمی',
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان پروژه')),
                ('researcher', models.CharField(max_length=200, verbose_name='محقق')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='بودجه')),
                ('status', models.CharField(choices=[('ongoing', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('pending', 'در انتظار')], default='ongoing', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پروژه پژوهشی',
                'verbose_name_plural': 'پروژه\u200cهای پژوهشی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان پایان\u200cنامه')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('supervisor', models.CharField(max_length=200, verbose_name='استاد راهنما')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='دانشکده')),
                ('degree', models.CharField(choices=[('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], default='master', max_length=10, verbose_name='مقطع')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('abstract', models.TextField(verbose_name='چکیده')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='کلیدواژه\u200cها')),
                ('file', models.FileField(blank=True, null=True, upload_to='theses/', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'پایان\u200cنامه',
                'verbose_name_plural': 'پایان\u200cنامه\u200cها',
                'ordering': ['-year'],
            },
        ),
    ]
