# Generated by Django 5.2.3 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypartnership',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='industrypartnership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='industrypartnership',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='industrypartnership',
            name='website',
            field=models.URLField(blank=True, verbose_name='وب\u200cسایت'),
        ),
    ]
