# Generated by Django 5.2.3 on 2026-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_sync_model_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['category', 'order', 'title'], 'verbose_name': 'مجله علمی', 'verbose_name_plural': 'مجلات علمی'},
        ),
        migrations.AddField(
            model_name='journal',
            name='category',
            field=models.CharField(choices=[('scientific', 'نشریه\u200cهای علمی - پژوهشی'), ('online_sub', 'نشریات دارای اشتراک on-line'), ('other', 'سایر')], default='scientific', max_length=20, verbose_name='دسته'),
        ),
        migrations.AddField(
            model_name='journal',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
