# Generated by Django 5.2.3 on 2026-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان رویداد')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='ساعت')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='مکان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('is_featured', models.BooleanField(default=False, verbose_name='برجسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('admission', 'پذیرش'), ('academic', 'آموزشی'), ('financial', 'مالی'), ('research', 'پژوهشی')], default='general', max_length=20, verbose_name='دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon', models.CharField(default='fas fa-link', max_length=100, verbose_name='آیکون (FontAwesome)')),
                ('url', models.CharField(max_length=200, verbose_name='آدرس')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='رنگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسترسی سریع',
                'verbose_name_plural': 'دسترسی\u200cهای سریع',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name_fa', models.CharField(default='دانشگاه جامع علمی کاربردی', max_length=200, verbose_name='نام دانشگاه (فارسی)')),
                ('university_name_en', models.CharField(default='Jame University', max_length=200, verbose_name='نام دانشگاه (انگلیسی)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاویکون')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('twitter', models.URLField(blank=True, verbose_name='توییتر')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('youtube', models.URLField(blank=True, verbose_name='یوتیوب')),
                ('about_short', models.TextField(blank=True, verbose_name='معرفی کوتاه')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعت کاری')),
                ('map_embed', models.TextField(blank=True, verbose_name='کد نقشه')),
                ('established_year', models.CharField(blank=True, max_length=10, verbose_name='سال تأسیس')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='متن لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['order'],
            },
        ),
    ]
