# Generated by Django 5.2.3 on 2026-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('founder', 'هیات موسس'), ('trustee', 'هیات امنا')], max_length=20, verbose_name='نوع هیات')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='عنوان/سمت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board_members/', verbose_name='تصویر')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('education', models.CharField(blank=True, max_length=300, verbose_name='تحصیلات')),
                ('specialization', models.CharField(blank=True, max_length=300, verbose_name='تخصص')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عضو هیات',
                'verbose_name_plural': 'اعضای هیات',
                'ordering': ['board_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CityAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام جاذبه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city/attractions/', verbose_name='تصویر')),
                ('category', models.CharField(blank=True, help_text='مثلاً: تاریخی، طبیعی، مذهبی، گردشگری', max_length=100, verbose_name='دسته\u200cبندی')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'جاذبه گردشگری',
                'verbose_name_plural': 'جاذبه\u200cهای گردشگری',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بخش')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city/', verbose_name='تصویر')),
                ('icon', models.CharField(blank=True, default='fas fa-city', max_length=100, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اطلاعات شهر',
                'verbose_name_plural': 'اطلاعات شهر بهنمیر',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان هدف')),
                ('description', models.TextField(blank=True, verbose_name='شرح هدف')),
                ('goal_type', models.CharField(choices=[('strategic', 'هدف راهبردی'), ('educational', 'هدف آموزشی'), ('research', 'هدف پژوهشی'), ('cultural', 'هدف فرهنگی'), ('social', 'هدف اجتماعی')], default='strategic', max_length=20, verbose_name='نوع هدف')),
                ('icon', models.CharField(blank=True, default='fas fa-bullseye', max_length=100, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'هدف موسسه',
                'verbose_name_plural': 'اهداف موسسه',
                'ordering': ['goal_type', 'order'],
            },
        ),
    ]
