# Generated by Django 5.2.3 on 2026-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boardmember_cityattraction_cityinfo_institutiongoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyVice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vice_type', models.CharField(choices=[('education', 'معاونت آموزشی'), ('research', 'معاونت پژوهشی'), ('student', 'معاونت دانشجویی'), ('admin_finance', 'معاونت اداری و مالی'), ('cultural', 'معاونت فرهنگی'), ('planning', 'معاونت برنامه\u200cریزی و توسعه'), ('international', 'معاونت بین\u200cالملل')], max_length=30, verbose_name='نوع معاونت')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('academic_rank', models.CharField(blank=True, max_length=200, verbose_name='مرتبه علمی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deputies/', verbose_name='تصویر')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('education', models.TextField(blank=True, verbose_name='سوابق تحصیلی')),
                ('resume', models.TextField(blank=True, verbose_name='سوابق اجرایی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='اتاق')),
                ('office_description', models.TextField(blank=True, verbose_name='شرح وظایف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'معاون دانشگاه',
                'verbose_name_plural': 'معاونین دانشگاه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InternationalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('activity_type', models.CharField(choices=[('agreement', 'تفاهم\u200cنامه'), ('exchange', 'تبادل دانشجو'), ('joint_research', 'پژوهش مشترک'), ('conference', 'کنفرانس بین\u200cالمللی'), ('scholarship', 'بورسیه')], default='agreement', max_length=20, verbose_name='نوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('partner_institution', models.CharField(blank=True, max_length=300, verbose_name='موسسه طرف قرارداد')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='کشور')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('document', models.FileField(blank=True, null=True, upload_to='international/docs/', verbose_name='سند / فایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'فعالیت بین\u200cالملل',
                'verbose_name_plural': 'فعالیت\u200cهای بین\u200cالملل',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InternationalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='معرفی دفتر')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='مدیر دفتر')),
                ('manager_photo', models.ImageField(blank=True, null=True, upload_to='international/', verbose_name='تصویر مدیر')),
                ('manager_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مدیر')),
                ('manager_phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن مدیر')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='تلفن دفتر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل دفتر')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'دفتر بین\u200cالملل',
                'verbose_name_plural': 'دفتر همکاری\u200cهای علمی و بین\u200cالملل',
            },
        ),
        migrations.CreateModel(
            name='PresidencyOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_name', models.CharField(blank=True, max_length=200, verbose_name='نام رئیس')),
                ('president_title', models.CharField(blank=True, max_length=300, verbose_name='درجه علمی / عنوان')),
                ('president_photo', models.ImageField(blank=True, null=True, upload_to='presidency/', verbose_name='تصویر رئیس')),
                ('president_bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('president_education', models.TextField(blank=True, verbose_name='سوابق تحصیلی')),
                ('president_resume', models.TextField(blank=True, verbose_name='سوابق اجرایی')),
                ('president_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('president_phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('president_message', models.TextField(blank=True, verbose_name='پیام رئیس')),
                ('office_address', models.TextField(blank=True, verbose_name='آدرس دفتر')),
                ('office_phone', models.CharField(blank=True, max_length=100, verbose_name='تلفن دفتر')),
                ('office_fax', models.CharField(blank=True, max_length=100, verbose_name='فکس')),
                ('office_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل دفتر')),
                ('office_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعات کاری')),
            ],
            options={
                'verbose_name': 'دفتر ریاست',
                'verbose_name_plural': 'دفتر ریاست',
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pr/press/', verbose_name='تصویر')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اطلاعیه روابط عمومی',
                'verbose_name_plural': 'اطلاعیه\u200cهای روابط عمومی',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='معرفی روابط عمومی')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='مدیر روابط عمومی')),
                ('manager_photo', models.ImageField(blank=True, null=True, upload_to='pr/', verbose_name='تصویر مدیر')),
                ('manager_bio', models.TextField(blank=True, verbose_name='بیوگرافی مدیر')),
                ('manager_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('manager_phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='تلفن روابط عمومی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل روابط عمومی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('duties', models.TextField(blank=True, verbose_name='شرح وظایف')),
            ],
            options={
                'verbose_name': 'روابط عمومی',
                'verbose_name_plural': 'مدیریت روابط عمومی',
            },
        ),
        migrations.CreateModel(
            name='SecurityOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='معرفی حراست')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='مسئول حراست')),
                ('manager_photo', models.ImageField(blank=True, null=True, upload_to='security/', verbose_name='تصویر')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='تلفن')),
                ('emergency_phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن اضطراری')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('duties', models.TextField(blank=True, verbose_name='وظایف و مسئولیت\u200cها')),
                ('regulations', models.TextField(blank=True, verbose_name='آیین\u200cنامه\u200cها و مقررات')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعات کاری')),
            ],
            options={
                'verbose_name': 'حراست',
                'verbose_name_plural': 'دفتر حراست',
            },
        ),
    ]
