# Generated by Django 5.2.3 on 2026-07-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deputyvice_internationalactivity_internationaloffice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VicePresidency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vice_type', models.CharField(choices=[('education', 'معاونت آموزشی و تحصیلات تکمیلی'), ('student', 'معاونت دانشجویی و فرهنگی'), ('admin_finance', 'معاونت اداری و مالی'), ('construction', 'معاونت فنی و عمرانی'), ('research', 'معاونت پژوهشی و فناوری')], max_length=20, unique=True, verbose_name='نوع معاونت')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='نام معاون')),
                ('academic_rank', models.CharField(blank=True, max_length=200, verbose_name='مرتبه علمی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vices/', verbose_name='تصویر')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('education', models.TextField(blank=True, verbose_name='سوابق تحصیلی')),
                ('resume', models.TextField(blank=True, verbose_name='سوابق اجرایی')),
                ('message', models.TextField(blank=True, verbose_name='پیام معاون')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='اتاق')),
                ('description', models.TextField(blank=True, verbose_name='معرفی و شرح فعالیت معاونت')),
                ('duties', models.TextField(blank=True, verbose_name='شرح وظایف')),
                ('goals', models.TextField(blank=True, verbose_name='اهداف معاونت')),
                ('achievements', models.TextField(blank=True, verbose_name='دستاوردها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'معاونت',
                'verbose_name_plural': 'معاونت\u200cها',
                'ordering': ['vice_type'],
            },
        ),
        migrations.CreateModel(
            name='ViceAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(blank=True, help_text='مثلاً: در حال اجرا، تکمیل\u200cشده', max_length=100, verbose_name='وضعیت')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='سال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vices/projects/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('vice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.vicepresidency', verbose_name='معاونت')),
            ],
            options={
                'verbose_name': 'دستاورد / طرح معاونت',
                'verbose_name_plural': 'دستاوردها / طرح\u200cهای معاونت',
                'ordering': ['vice', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ViceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام واحد')),
                ('manager', models.CharField(blank=True, max_length=200, verbose_name='مدیر / مسئول')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('duties', models.TextField(blank=True, verbose_name='شرح وظایف')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('vice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.vicepresidency', verbose_name='معاونت')),
            ],
            options={
                'verbose_name': 'واحد زیرمجموعه معاونت',
                'verbose_name_plural': 'واحدهای زیرمجموعه معاونت',
                'ordering': ['vice', 'order'],
            },
        ),
    ]
