# Generated by Django 5.2.3 on 2026-07-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vicepresidency_viceachievement_viceunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('president', 'ریاست دانشگاه'), ('vice', 'معاونت'), ('unit', 'واحد/اداره'), ('department', 'دانشکده'), ('group', 'گروه آموزشی'), ('office', 'دفتر'), ('section', 'بخش')], max_length=20, verbose_name='نوع واحد')),
                ('name', models.CharField(max_length=200, verbose_name='نام واحد')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='عنوان/سمت')),
                ('person_name', models.CharField(blank=True, max_length=200, verbose_name='نام مسئول')),
                ('person_photo', models.ImageField(blank=True, null=True, upload_to='org_chart/', verbose_name='تصویر مسئول')),
                ('person_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('person_phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('description', models.TextField(blank=True, verbose_name='شرح وظایف')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل')),
                ('staff_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='تعداد پرسنل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organizationalchart', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'چارت سازمانی',
                'verbose_name_plural': 'چارت سازمانی',
                'ordering': ['parent', 'order', 'name'],
            },
        ),
    ]
