# Generated by Django 5.2.3 on 2026-07-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organizationalchart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalchart',
            options={'ordering': ['order', 'name'], 'verbose_name': 'چارت سازمانی', 'verbose_name_plural': 'چارت سازمانی'},
        ),
    ]
