# Generated by Django 5.2.3 on 2026-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_organizationalchart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='history_text',
            field=models.TextField(blank=True, verbose_name='تاریخچه دانشگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_text',
            field=models.TextField(blank=True, verbose_name='مأموریت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='values_text',
            field=models.TextField(blank=True, verbose_name='ارزش\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_text',
            field=models.TextField(blank=True, verbose_name='چشم\u200cانداز'),
        ),
    ]
