# Generated by Django 5.2.3 on 2026-07-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_history_text_sitesettings_mission_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vicepresidency',
            name='vice_type',
            field=models.CharField(choices=[('education', 'معاونت آموزشی و تحصیلات تکمیلی'), ('student', 'معاونت دانشجویی و فرهنگی'), ('admin_finance', 'معاونت اداری و مالی'), ('construction', 'معاونت فنی و عمرانی'), ('research', 'معاونت پژوهشی و فناوری'), ('development', 'معاونت توسعه و منابع انسانی')], max_length=20, unique=True, verbose_name='نوع معاونت'),
        ),
    ]
