# Generated by Django 5.2.3 on 2026-07-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_vicepresidency_vice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='badge_color',
            field=models.CharField(blank=True, choices=[('danger', 'قرمز (فوری)'), ('warning', 'زرد (هشدار)'), ('success', 'سبز (اطلاع)'), ('info', 'آبی روشن'), ('primary', 'آبی'), ('dark', 'تیره')], default='danger', help_text='رنگ پس\u200cزمینه برچسب اعلان', max_length=20, verbose_name='رنگ اعلان'),
        ),
        migrations.AddField(
            model_name='slider',
            name='badge_icon',
            field=models.CharField(blank=True, default='fas fa-bell', help_text='مثال: fas fa-calendar-alt  یا  fas fa-bell', max_length=80, verbose_name='آیکون اعلان (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='slider',
            name='badge_text',
            field=models.CharField(blank=True, help_text='این متن به صورت برچسب روی تصویر اسلایدر نمایش داده می\u200cشود', max_length=150, verbose_name='متن اعلان مهم'),
        ),
    ]
