# Generated by Django 5.2.3 on 2026-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_slider_badge_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اصلی')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='landing_sliders/', verbose_name='تصویر پس\u200cزمینه')),
                ('badge_text', models.CharField(blank=True, help_text='این متن به صورت برچسب رنگی روی تصویر نمایش داده می\u200cشود (اختیاری)', max_length=150, verbose_name='متن اعلان / خبر مهم')),
                ('badge_color', models.CharField(blank=True, choices=[('danger', 'قرمز (فوری)'), ('warning', 'زرد (هشدار)'), ('success', 'سبز (اطلاع)'), ('info', 'آبی روشن'), ('gold', 'طلایی'), ('dark', 'تیره')], default='danger', max_length=20, verbose_name='رنگ اعلان')),
                ('badge_icon', models.CharField(blank=True, default='fas fa-bell', help_text='کلاس FontAwesome — مثال: fas fa-calendar-alt', max_length=80, verbose_name='آیکون اعلان')),
                ('btn1_text', models.CharField(blank=True, default='شروع پذیرش', max_length=80, verbose_name='متن دکمه اول')),
                ('btn1_url', models.CharField(blank=True, default='/admissions/', max_length=200, verbose_name='لینک دکمه اول')),
                ('btn2_text', models.CharField(blank=True, default='کاوش در دانشگاه', max_length=80, verbose_name='متن دکمه دوم')),
                ('btn2_url', models.CharField(blank=True, default='/خانه/', max_length=200, verbose_name='لینک دکمه دوم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلایدر لندینگ',
                'verbose_name_plural': 'اسلایدرهای لندینگ',
                'ordering': ['order'],
            },
        ),
    ]
