# Generated by Django 5.2.3 on 2026-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_unify_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='شبا')),
                ('account_holder', models.CharField(blank=True, max_length=200, verbose_name='صاحب حساب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('regulation', 'آیین\u200cنامه'), ('form', 'فرم'), ('guide', 'راهنما'), ('other', 'سایر')], default='form', max_length=20, verbose_name='دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='فایل')),
                ('external_url', models.URLField(blank=True, help_text='اگر فایل آپلود نشده، از این لینک استفاده می\u200cشود', verbose_name='لینک خارجی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'آیین\u200cنامه / فرم',
                'verbose_name_plural': 'آیین\u200cنامه\u200cها و فرم\u200cها',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(db_index=True, max_length=10, verbose_name='کد ملی')),
                ('student_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='شماره دانشجویی')),
                ('payment_id', models.CharField(max_length=50, verbose_name='شناسه واریز')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='سال تحصیلی')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شناسه واریز',
                'verbose_name_plural': 'شناسه\u200cهای واریز',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='external_admin_url',
            field=models.URLField(blank=True, help_text='سامانه مکاتبات/اتوماسیون اداری؛ تغذیه و خوابگاه پشتیبانی نمی\u200cشود', verbose_name='لینک اتوماسیون اداری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='external_lms_url',
            field=models.URLField(blank=True, help_text='در صورت خالی بودن، به پنل داخلی هدایت می\u200cشود', verbose_name='لینک سامانه آموزشی خارجی'),
        ),
    ]
