# Generated by Django 5.2.3 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aab_parity_bank_docs_presidency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityinfo',
            options={'ordering': ['order'], 'verbose_name': 'اطلاعات شهر', 'verbose_name_plural': 'اطلاعات شهر'},
        ),
        migrations.AlterModelOptions(
            name='internationaloffice',
            options={'verbose_name': 'دفتر بین\u200cالملل', 'verbose_name_plural': 'دفتر بین\u200cالملل'},
        ),
        migrations.AlterModelOptions(
            name='publicrelations',
            options={'verbose_name': 'روابط عمومی', 'verbose_name_plural': 'روابط عمومی'},
        ),
        migrations.AlterModelOptions(
            name='viceachievement',
            options={'ordering': ['vice', 'order'], 'verbose_name': 'دستاورد معاونت', 'verbose_name_plural': 'دستاوردهای معاونت'},
        ),
        migrations.AlterModelOptions(
            name='viceunit',
            options={'ordering': ['vice', 'order'], 'verbose_name': 'واحد معاونت', 'verbose_name_plural': 'واحدهای معاونت'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='university_name_fa',
            field=models.CharField(default='موسسه آموزش عالی علامه امینی بهنمیر', max_length=200, verbose_name='نام دانشگاه (فارسی)'),
        ),
    ]
