# Generated by Django 5.2.3 on 2026-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sync_model_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stat_faculty',
            field=models.PositiveIntegerField(default=200, verbose_name='تعداد عضو هیئت علمی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_majors',
            field=models.PositiveIntegerField(default=50, verbose_name='تعداد رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_students',
            field=models.PositiveIntegerField(default=5000, verbose_name='تعداد دانشجوی فعال'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_years',
            field=models.PositiveIntegerField(default=30, verbose_name='سال سابقه'),
        ),
    ]
