# Generated by Django 5.2.3 on 2026-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_site_stats_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateStudiesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='مدیر تحصیلات تکمیلی')),
                ('intro', models.TextField(blank=True, verbose_name='معرفی')),
            ],
            options={
                'verbose_name': 'تحصیلات تکمیلی',
                'verbose_name_plural': 'تحصیلات تکمیلی',
            },
        ),
        migrations.CreateModel(
            name='PresidencyOfficeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'واحد دفتر ریاست',
                'verbose_name_plural': 'واحدهای دفتر ریاست',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='downloadabledocument',
            options={'ordering': ['section', 'category', 'order', '-created_at'], 'verbose_name': 'آیین\u200cنامه / فرم', 'verbose_name_plural': 'آیین\u200cنامه\u200cها و فرم\u200cها'},
        ),
        migrations.AddField(
            model_name='downloadabledocument',
            name='section',
            field=models.CharField(blank=True, choices=[('', 'عمومی'), ('graduate', 'تحصیلات تکمیلی')], default='', help_text='مثلاً آیین\u200cنامه/فرم ویژه تحصیلات تکمیلی', max_length=20, verbose_name='بخش'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='office_duties',
            field=models.TextField(blank=True, verbose_name='شرح وظایف دفتر ریاست'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='office_manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='مدیر دفتر ریاست'),
        ),
    ]
