# Generated by Django 5.2.3 on 2026-07-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_graduate_presidency_official'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['category', 'order'], 'verbose_name': 'دسترسی سریع', 'verbose_name_plural': 'دسترسی\u200cهای سریع'},
        ),
        migrations.AddField(
            model_name='quicklink',
            name='category',
            field=models.CharField(choices=[('eservice', 'خدمات الکترونیکی'), ('quick_access', 'دسترسی سریع'), ('home', 'صفحه اصلی')], default='home', max_length=20, verbose_name='دسته'),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='باز شدن در تب جدید'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='external_dorm_url',
            field=models.URLField(blank=True, verbose_name='لینک اتوماسیون خوابگاه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='external_food_url',
            field=models.URLField(blank=True, verbose_name='لینک اتوماسیون تغذیه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='external_publications_url',
            field=models.URLField(blank=True, verbose_name='لینک سامانه نشریات'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='url',
            field=models.CharField(max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='external_admin_url',
            field=models.URLField(blank=True, help_text='سامانه مکاتبات/اتوماسیون اداری', verbose_name='لینک اتوماسیون اداری'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='external_lms_url',
            field=models.URLField(blank=True, help_text='مثلاً سامانه خدمات آموزشی samaweb', verbose_name='لینک سامانه آموزشی خارجی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='university_name_en',
            field=models.CharField(default='Allameh Amini Higher Education Institute', max_length=200, verbose_name='نام دانشگاه (انگلیسی)'),
        ),
    ]
