# Generated by Django 5.2.3 on 2026-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_food_dorm_automation_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadabledocument',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/word/', verbose_name='فایل Word'),
        ),
        migrations.AlterField(
            model_name='downloadabledocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='فایل PDF'),
        ),
    ]
