# Generated by Django 5.2.3 on 2026-07-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_word_file_to_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadabledocument',
            options={'ordering': ['degree_level', 'section', 'category', 'order', '-created_at'], 'verbose_name': 'آیین\u200cنامه / فرم', 'verbose_name_plural': 'آیین\u200cنامه\u200cها و فرم\u200cها'},
        ),
        migrations.AddField(
            model_name='downloadabledocument',
            name='degree_level',
            field=models.CharField(blank=True, choices=[('', 'عمومی (بدون پوشه مقطع)'), ('master', 'کارشناسی ارشد'), ('bachelor_continuous', 'کارشناسی پیوسته'), ('bachelor_discontinuous', 'کارشناسی ناپیوسته'), ('associate', 'کاردانی ناپیوسته'), ('associate_tech', 'کاردانی فنی')], db_index=True, default='', help_text='سند در کدام پوشه مقطع نمایش داده شود', max_length=40, verbose_name='مقطع / پوشه'),
        ),
    ]
