# Generated by Django 5.2.3 on 2026-07-24 07:47

from django.db import migrations, models


def forwards_empty_to_general(apps, schema_editor):
    DownloadableDocument = apps.get_model('core', 'DownloadableDocument')
    DownloadableDocument.objects.filter(degree_level='').update(degree_level='general')


def backwards_general_to_empty(apps, schema_editor):
    DownloadableDocument = apps.get_model('core', 'DownloadableDocument')
    DownloadableDocument.objects.filter(degree_level='general').update(degree_level='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_document_degree_level'),
    ]

    operations = [
        migrations.RunPython(forwards_empty_to_general, backwards_general_to_empty),
        migrations.AlterField(
            model_name='downloadabledocument',
            name='degree_level',
            field=models.CharField(choices=[('general', 'عمومی (بدون پوشه مقطع)'), ('master', 'کارشناسی ارشد'), ('bachelor_continuous', 'کارشناسی پیوسته'), ('bachelor_discontinuous', 'کارشناسی ناپیوسته'), ('associate', 'کاردانی ناپیوسته'), ('associate_tech', 'کاردانی فنی')], db_index=True, default='general', help_text='سند در کدام پوشه مقطع نمایش داده شود — حتماً یکی را انتخاب کنید', max_length=40, verbose_name='مقطع / پوشه'),
        ),
    ]
