# Generated by Django 5.2.3 on 2026-07-24 07:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_degree_level_general_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadabledocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models._document_pdf_upload_to, verbose_name='فایل PDF'),
        ),
        migrations.AlterField(
            model_name='downloadabledocument',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models._document_word_upload_to, verbose_name='فایل Word'),
        ),
    ]
