# Generated by Django 5.2.3 on 2026-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_canonical_document_degrees'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='توضیح کوتاه')),
                ('icon', models.CharField(default='fa-star', help_text='کلاس Font Awesome، مثلاً fa-graduation-cap', max_length=60, verbose_name='آیکون')),
                ('tone', models.CharField(choices=[('blue', 'آبی'), ('green', 'سبز'), ('gold', 'طلایی'), ('violet', 'بنفش'), ('red', 'قرمز'), ('amber', 'کهربایی'), ('teal', 'فیروزه\u200cای')], default='blue', max_length=10, verbose_name='رنگ آیکون')),
                ('image', models.ImageField(blank=True, help_text='اختیاری — اگر بگذارید جای آیکون نمایش داده می\u200cشود.', null=True, upload_to='features/', verbose_name='تصویر')),
                ('link', models.CharField(blank=True, default='', max_length=300, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مزیت تحصیل',
                'verbose_name_plural': 'مزایای تحصیل (صفحه اصلی)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('stats', 'نوار آمار'), ('timeline', 'تقویم آموزشی'), ('features', 'مزایای تحصیل'), ('quicklinks', 'دسترسی سریع'), ('news', 'اخبار و اطلاعیه\u200cها'), ('departments', 'دانشکده\u200cها و گروه\u200cها'), ('faculty', 'هیئت علمی'), ('events', 'رویدادها'), ('gallery', 'گالری تصاویر'), ('alumni', 'فارغ\u200cالتحصیلان'), ('faq', 'پرسش\u200cهای متداول'), ('cta', 'فراخوان پایانی')], max_length=30, unique=True, verbose_name='بخش')),
                ('title', models.CharField(blank=True, help_text='خالی = عنوان پیش\u200cفرض قالب حفظ می\u200cشود.', max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='تصویر پس\u200cزمینه')),
                ('overlay', models.CharField(choices=[('none', 'بدون پوشش'), ('light', 'پوشش روشن'), ('dark', 'پوشش تیره'), ('navy', 'پوشش سرمه\u200cای')], default='light', help_text='برای خوانا ماندن متن روی تصویر.', max_length=10, verbose_name='پوشش روی تصویر')),
                ('is_visible', models.BooleanField(default=True, help_text='برداشتن تیک، کل بخش را از صفحهٔ اصلی حذف می\u200cکند.', verbose_name='نمایش این بخش')),
            ],
            options={
                'verbose_name': 'بخش صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای صفحه اصلی (تصویر و عنوان)',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='university_name_fa',
            field=models.CharField(default='موسسه آموزش عالی علامه امینی', max_length=200, verbose_name='نام دانشگاه (فارسی)'),
        ),
    ]
