# Generated by Django 5.2.3 on 2026-08-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_homefeature_homesection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadabledocument',
            name='section',
            field=models.CharField(blank=True, choices=[('', 'عمومی'), ('academic', 'آموزش'), ('research', 'پژوهش'), ('graduate', 'تحصیلات تکمیلی')], default='', help_text='مثلاً آیین\u200cنامه/فرم ویژه تحصیلات تکمیلی', max_length=20, verbose_name='بخش'),
        ),
    ]
