# Generated by Django 5.2.3 on 2026-08-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_welfare_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='duties',
            field=models.TextField(blank=True, help_text='هر وظیفه در یک خط جدا بنویسید؛ فهرست\u200cوار نمایش داده می\u200cشود.', verbose_name='شرح وظایف'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='extension',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره داخلی'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='icon',
            field=models.CharField(default='fa-building', help_text='کلاس Font Awesome، مثلاً fa-user-tie', max_length=60, verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='location',
            field=models.CharField(blank=True, help_text='مثلاً: ساختمان مرکزی، طبقه دوم، اتاق ۲۰۴', max_length=200, verbose_name='محل استقرار'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مسئول'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='manager_photo',
            field=models.ImageField(blank=True, null=True, upload_to='presidency/units/', verbose_name='تصویر مسئول'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='manager_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='سمت مسئول'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='office_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='ساعات مراجعه'),
        ),
        migrations.AddField(
            model_name='presidencyofficeunit',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='تلفن'),
        ),
    ]
