# Generated by Django 5.2.3 on 2026-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_presidency_unit_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شد'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('last_error', models.CharField(blank=True, max_length=300, verbose_name='آخرین خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'پیامک در صف',
                'verbose_name_plural': 'صف پیامک',
                'ordering': ['-created_at'],
            },
        ),
    ]
