# Generated by Django 5.2.3 on 2026-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sms_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_cv',
            field=models.FileField(blank=True, help_text='PDF — دکمهٔ دانلود زیر مشخصات دیده می\u200cشود.', null=True, upload_to='presidency/cv/', verbose_name='فایل رزومه'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_orcid',
            field=models.CharField(blank=True, help_text='فقط شناسه، مثلاً 0000-0002-1825-0097', max_length=40, verbose_name='شناسهٔ ORCID'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_research',
            field=models.TextField(blank=True, help_text='هر زمینه در یک خط جدا؛ برچسب\u200cوار نمایش داده می\u200cشود.', verbose_name='زمینه\u200cهای پژوهشی'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_scholar',
            field=models.URLField(blank=True, verbose_name='گوگل اسکولار'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_website',
            field=models.URLField(blank=True, help_text='نشانی کامل با https، مثلاً https://example.com', verbose_name='وب\u200cسایت / صفحهٔ علمی'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_website_label',
            field=models.CharField(blank=True, help_text='متنی که روی دکمه دیده می\u200cشود؛ خالی بماند نام دامنه می\u200cآید.', max_length=120, verbose_name='عنوان وب\u200cسایت'),
        ),
    ]
