# Generated by Django 5.2.3 on 2026-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_presidencyoffice_president_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_ink',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند. مقدار باید شش\u200cرقمی هگز باشد، مثل #0d2137.', max_length=9, verbose_name='رنگ عنوان و تاریخ (حالت روشن)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_ink_dark',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند. مقدار باید شش\u200cرقمی هگز باشد، مثل #0d2137.', max_length=9, verbose_name='رنگ عنوان و تاریخ (حالت تیره)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_ink_soft',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند. مقدار باید شش\u200cرقمی هگز باشد، مثل #0d2137.', max_length=9, verbose_name='رنگ توضیحات (حالت روشن)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_ink_soft_dark',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند. مقدار باید شش\u200cرقمی هگز باشد، مثل #0d2137.', max_length=9, verbose_name='رنگ توضیحات (حالت تیره)'),
        ),
    ]
