# Generated by Django 5.2.3 on 2026-08-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sitesettings_calendar_ink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='world_class_logo',
            field=models.ImageField(blank=True, help_text='در دو سوی عنوان سربرگ و در صفحهٔ ریاست نمایش داده می\u200cشود. ترجیحاً PNG با پس\u200cزمینهٔ شفاف و مربع.', null=True, upload_to='site/', verbose_name='نشان کلاس جهانی (WCU)'),
        ),
    ]
