# Generated by Django 5.2.3 on 2026-08-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sitesettings_world_class_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presidencyoffice',
            name='president_cv',
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_awards',
            field=models.TextField(blank=True, help_text='هر مورد در یک خط جدا.', verbose_name='جوایز و افتخارات علمی'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_highlights',
            field=models.TextField(blank=True, help_text='هر خط به شکل «عدد | برچسب»، مثلاً:<br><code>۳۱ | جلد کتاب دانشگاهی</code><br>بالای رزومه به\u200cصورت کارت\u200cهای عددی دیده می\u200cشوند.', verbose_name='آمار برجسته'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_memberships',
            field=models.TextField(blank=True, help_text='هر مورد در یک خط جدا.', verbose_name='عضویت در مراکز علمی و پژوهشی'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_teaching',
            field=models.TextField(blank=True, help_text='هر درس در یک خط جدا.', verbose_name='سوابق تدریسی'),
        ),
    ]
