# Generated by Django 5.2.3 on 2026-08-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_presidencyoffice_president_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidencyoffice',
            name='wcu_motto',
            field=models.TextField(blank=True, help_text='زیر عنوان، داخل گیومه نمایش داده می\u200cشود.', verbose_name='شعار سایت تخصصی'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='wcu_title',
            field=models.CharField(blank=True, help_text='یک خط، درشت و رنگی زیر نشان کلاس جهانی.', max_length=200, verbose_name='عنوان سایت تخصصی'),
        ),
    ]
