# Generated by Django 5.2.3 on 2026-08-26 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_presidencyoffice_wcu_motto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidencyoffice',
            name='office_floor',
            field=models.CharField(blank=True, help_text='مثلاً «طبقهٔ سوم». پیش از این در قالب ثابت نوشته شده بود و با نشانیِ ثبت\u200cشده نمی\u200cخواند — یکی سوم می\u200cگفت و دیگری دوم.', max_length=60, verbose_name='طبقهٔ دفتر ریاست'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='president_cv',
            field=models.FileField(blank=True, help_text='PDF یا Word. دکمهٔ «رزومه» در صفحهٔ ریاست به همین فایل می\u200cرود.', null=True, upload_to='presidency/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='فایل رزومه'),
        ),
    ]
