# Generated by Django 5.2.3 on 2026-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_presidencyoffice_office_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidencyoffice',
            name='tile_color_address',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند.', max_length=9, verbose_name='رنگ کارت نشانی'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='tile_color_email',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند.', max_length=9, verbose_name='رنگ کارت ایمیل'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='tile_color_floor',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند.', max_length=9, verbose_name='رنگ کارت دفتر ریاست'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='tile_color_hours',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند.', max_length=9, verbose_name='رنگ کارت روزهای مراجعه'),
        ),
        migrations.AddField(
            model_name='presidencyoffice',
            name='tile_color_phone',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا رنگ پیش\u200cفرض بماند.', max_length=9, verbose_name='رنگ کارت تلفن'),
        ),
    ]
