# Generated by Django 5.2.3 on 2026-08-27 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_presidencyoffice_tile_color_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_slider_count',
            field=models.PositiveSmallIntegerField(default=7, help_text='چند اسلاید از فهرست اسلایدها روی صفحهٔ اصلی بیاید. اسلایدهای بیشتر از این عدد ثبت می\u200cمانند ولی نمایش داده نمی\u200cشوند. هر اسلاید یک عکس است و وزن صفحه را بالا می\u200cبرد، پس سقف 12 گذاشته شده.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='تعداد اسلاید صفحهٔ اصلی'),
        ),
    ]
