# Generated by Django 5.2.3 on 2026-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sitesettings_home_slider_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شورا')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نشانی')),
                ('short_description', models.CharField(blank=True, help_text='یک جمله؛ زیر نام شورا در فهرست دیده می\u200cشود.', max_length=300, verbose_name='معرفی کوتاه')),
                ('duties', models.TextField(blank=True, help_text='هر وظیفه در یک خط.', verbose_name='شرح وظایف')),
                ('members', models.TextField(blank=True, help_text='هر عضو در یک خط؛ مثلاً «دکتر … — رئیس شورا».', verbose_name='اعضا')),
                ('head', models.CharField(blank=True, max_length=200, verbose_name='رئیس شورا')),
                ('icon', models.CharField(default='fa-users-rectangle', help_text='نام آیکون Font Awesome، بدون پیشوند fas.', max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شورا',
                'verbose_name_plural': 'شوراها',
                'ordering': ['order', 'name'],
            },
        ),
    ]
