# Generated by Django 5.2.3 on 2026-08-27 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='faculties_pdf',
            field=models.FileField(blank=True, help_text='صفحهٔ «دانشکده\u200cها» همین فایل را نشان می\u200cدهد. برای جایگزینی، فایل تازه را آپلود کنید.', null=True, upload_to='site/faculties/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='فایل رشته\u200cهای دانشکده\u200cها (PDF)'),
        ),
    ]
