# Generated by Django 5.2.3 on 2026-08-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sitesettings_faculties_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admission_poster',
            field=models.ImageField(blank=True, help_text='روی صفحهٔ اصلی یک باکس با همین عنوان می\u200cآید و با کلیک، این تصویر تمام\u200cصفحه نشان داده می\u200cشود.', null=True, upload_to='site/admission/', verbose_name='پوستر رشته\u200cهای پذیرش دانشجو'),
        ),
    ]
