# Generated by Django 5.2.3 on 2026-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_sitesettings_admission_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='world_class_url',
            field=models.URLField(blank=True, default='https://WCM-Society.Com', help_text='نشان کلاس جهانی در نوار بالای سایت به این نشانی می\u200cرود.', verbose_name='نشانی سایت کلاس جهانی'),
        ),
    ]
