# Generated by Django 5.2.3 on 2026-09-03 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_sitesettings_world_class_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='council_card_min_height',
            field=models.PositiveSmallIntegerField(default=220, help_text='ارتفاع حداقل هر کارت در صفحهٔ شوراها. اگر محتوای یک کارت طولانی\u200cتر شد، بلندتر نیز می\u200cتواند رشد کند.', validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(500)], verbose_name='حداقل ارتفاع کارت شورا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='council_card_min_width',
            field=models.PositiveSmallIntegerField(default=260, help_text='کارت\u200cهای صفحهٔ شوراها حداقل این عرض را می\u200cگیرند؛ با این مقدار می\u200cتوانید اندازهٔ باکس\u200cها را در فهرست شوراها تنظیم کنید.', validators=[django.core.validators.MinValueValidator(180), django.core.validators.MaxValueValidator(420)], verbose_name='حداقل عرض کارت شورا'),
        ),
    ]
