# Generated by Django 5.2.3 on 2026-09-03 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_seed_councils_from_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_height',
            field=models.PositiveSmallIntegerField(default=62, help_text='عدد کوچک\u200cتر یعنی تصویر کوچک\u200cتر. پیش\u200cفرض ۶۲.', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(90)], verbose_name='ارتفاع اسلایدر (درصد صفحه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_count',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='تعداد ردیف هر فهرست'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_enabled',
            field=models.BooleanField(default=True, help_text='برداشتن تیک، اسلایدر را دوباره تمام\u200cعرض می\u200cکند.', verbose_name='ستون اطلاع\u200cرسانی کنار اسلایدر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_show_announcements',
            field=models.BooleanField(default=True, verbose_name='اطلاعیه\u200cها در ستون'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_show_events',
            field=models.BooleanField(default=True, verbose_name='رویدادها در ستون'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_show_news',
            field=models.BooleanField(default=True, verbose_name='اخبار در ستون'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_width',
            field=models.PositiveSmallIntegerField(default=340, validators=[django.core.validators.MinValueValidator(240), django.core.validators.MaxValueValidator(520)], verbose_name='پهنای ستون اطلاع\u200cرسانی (پیکسل)'),
        ),
    ]
