# Generated by Django 5.2.3 on 2026-09-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_sitesettings_hero_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='کنار «تاریخچه مؤسسه» دیده می\u200cشود. اگر خالی باشد، عکس پیش\u200cفرض پردیس نمایش داده می\u200cشود. نسبت افقی (مثلاً ۱۶۰۰×۹۰۰) بهترین نتیجه را می\u200cدهد.', null=True, upload_to='site/about/', verbose_name='تصویر صفحهٔ معرفی موسسه'),
        ),
    ]
