# Generated by Django 5.2.3 on 2026-09-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_sitesettings_about_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'order'], 'verbose_name': 'سوال متداول', 'verbose_name_plural': 'پرسش\u200cهای متداول'},
        ),
    ]
