# Generated by Django 5.2.3 on 2026-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_faq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='key',
            field=models.CharField(choices=[('stats', 'نوار آمار'), ('timeline', 'تقویم آموزشی'), ('features', 'مزایای تحصیل'), ('quicklinks', 'دسترسی سریع'), ('news', 'اخبار و اطلاعیه\u200cها'), ('departments', 'دانشکده\u200cها و گروه\u200cها'), ('events', 'رویدادها'), ('gallery', 'گالری تصاویر'), ('alumni', 'فارغ\u200cالتحصیلان'), ('faq', 'پرسش\u200cهای متداول'), ('cta', 'فراخوان پایانی')], max_length=30, unique=True, verbose_name='بخش'),
        ),
    ]
