# Generated by Django 5.2.3 on 2026-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_homesection_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vicepresidency',
            name='title',
            field=models.CharField(blank=True, help_text='نامی که در منو و صفحهٔ معاونت دیده می\u200cشود. خالی بگذارید تا عنوان پیش\u200cفرض بماند.', max_length=120, verbose_name='عنوان معاونت'),
        ),
    ]
