# Generated by Django 5.2.3 on 2026-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_vicepresidency_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_tagline',
            field=models.CharField(blank=True, help_text='یک سطر زیر سرتیتر. خالی بگذارید تا نام موسسه بیاید.', max_length=120, verbose_name='زیرعنوان ستون اطلاع\u200cرسانی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_title',
            field=models.CharField(default='پایگاه خبری', help_text='سرتیتر بالای ستون کنار اسلایدر.', max_length=60, verbose_name='عنوان ستون اطلاع\u200cرسانی'),
        ),
    ]
