# Generated by Django 5.2.3 on 2026-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_sitesettings_hero_side_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='fit',
            field=models.CharField(blank=True, choices=[('', 'خودکار — از روی ابعاد تصویر'), ('cover', 'پر کردن قاب — عکس افقی'), ('contain', 'نمایش کامل — پوستر، اینفوگرافیک، عکس عمودی')], default='', help_text='قاب اسلایدر افقی است. عکس افقی قاب را پر می\u200cکند؛ پوستر و اینفوگرافیک باید کامل دیده شوند، وگرنه فقط نوار میانی\u200cشان می\u200cماند.', max_length=10, verbose_name='نحوهٔ نمایش تصویر'),
        ),
        migrations.AddField(
            model_name='slider',
            name='focus',
            field=models.CharField(choices=[('center', 'مرکز'), ('top', 'بالای تصویر'), ('bottom', 'پایین تصویر')], default='center', help_text='وقتی قاب پر می\u200cشود، کدام بخش تصویر باید بماند.', max_length=10, verbose_name='نقطهٔ مهم تصویر'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
