# Generated by Django 5.2.3 on 2026-09-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_backfill_slider_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='home_slider_count',
            field=models.PositiveSmallIntegerField(default=7, help_text='چند اسلاید از فهرست اسلایدها روی صفحهٔ اصلی بیاید. <strong>صفر یعنی همه</strong> — هر اسلاید فعالی که ساخته\u200cاید. سقفی در کار نیست: جز اسلاید اول، بقیه تا وقتی دیده نشوند دانلود نمی\u200cشوند.', verbose_name='تعداد اسلاید صفحهٔ اصلی'),
        ),
    ]
