# Generated by Django 5.2.3 on 2026-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_sitesettings_home_slider_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بخش')),
                ('subtitle', models.CharField(blank=True, help_text='یک سطر زیر عنوان. اختیاری.', max_length=300, verbose_name='زیرعنوان')),
                ('icon', models.CharField(blank=True, default='fas fa-circle-info', help_text='نام آیکون Font Awesome، مثلاً fas fa-award', max_length=60, verbose_name='آیکون')),
                ('body', models.TextField(blank=True, help_text='برای چیدمان «کارت\u200cهای چندتایی»، هر خط یک کارت می\u200cشود؛ اگر خط را با «|» دو تکه کنید، تکهٔ اول عنوان کارت است و تکهٔ دوم متنش.', verbose_name='متن')),
                ('image', models.ImageField(blank=True, help_text='فقط در چیدمان\u200cهایی که تصویر دارند دیده می\u200cشود.', null=True, upload_to='about/', verbose_name='تصویر')),
                ('layout', models.CharField(choices=[('text', 'فقط متن — تمام عرض'), ('image_end', 'متن راست، تصویر چپ'), ('image_start', 'تصویر راست، متن چپ'), ('cards', 'کارت\u200cهای چندتایی — هر خط یک کارت'), ('highlight', 'کادر برجسته — یک پیام کوتاه')], default='text', max_length=20, verbose_name='چیدمان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بخش صفحهٔ معرفی',
                'verbose_name_plural': 'بخش\u200cهای صفحهٔ معرفی',
                'ordering': ['order', 'id'],
            },
        ),
    ]
