# Generated by Django 5.2.3 on 2026-09-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='state_emblem',
            field=models.ImageField(blank=True, help_text='سمت چپ سربرگ، کنار «جمهوری اسلامی ایران». خالی بگذارید تا نشان پیش\u200cفرض بماند. PNG با پس\u200cزمینهٔ شفاف بهترین نتیجه را می\u200cدهد؛ نسبت عمودی (مثلاً ۱۸۲×۱۹۸).', null=True, upload_to='site/', verbose_name='ارم الله (نشان جمهوری اسلامی)'),
        ),
    ]
