# Generated by Django 5.2.3 on 2026-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_sitesettings_state_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='source_key',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
