# Generated by Django 5.2.3 on 2026-09-06 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_boardmember_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='state_emblem_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='اگر ارم شما کوچک\u200cتر یا بزرگ\u200cتر از حد به\u200cنظر می\u200cرسد، با همین عدد تنظیمش کنید. ۱۰۰ یعنی اندازهٔ عادی.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(150)], verbose_name='اندازهٔ ارم (درصد)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='state_emblem_style',
            field=models.CharField(blank=True, choices=[('', 'خودکار — بهترین حالت برای همین فایل'), ('original', 'رنگ اصلی تصویر'), ('bronze', 'هم\u200cرنگ با بنر (برنزی)')], default='', help_text='نشان پیش\u200cفرض یک خط\u200cنگارهٔ سفید است و باید برنزی شود تا روی زمینهٔ روشن دیده شود؛ ولی همان فیلتر، ارمِ رنگی را یک\u200cدست می\u200cکند. «خودکار» یعنی نشان پیش\u200cفرض برنزی و ارمِ آپلودی با رنگ خودش.', max_length=10, verbose_name='نمایش ارم'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='state_emblem',
            field=models.ImageField(blank=True, help_text='سمت چپ سربرگ، کنار «جمهوری اسلامی ایران». خالی بگذارید تا نشان پیش\u200cفرض بماند. PNG با پس\u200cزمینهٔ شفاف بهترین نتیجه را می\u200cدهد؛ نسبت عمودی (مثلاً ۱۸۲×۱۹۸).', null=True, upload_to='site/emblem/', verbose_name='ارم الله (نشان جمهوری اسلامی)'),
        ),
    ]
