# Generated by Django 5.2.3 on 2026-09-07 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_sitesettings_state_emblem_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ticker_hold_seconds',
            field=models.PositiveSmallIntegerField(default=2, help_text='خبر پیش از راه\u200cافتادن، این چند ثانیه کنار لبهٔ چپ می\u200cایستد تا خوانده شود. صفر یعنی بدون مکث.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='مکث در ابتدای حرکت (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ticker_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='هر اطلاعیه چند ثانیه طول بکشد تا از چپ به راست رد شود. عدد بزرگ\u200cتر یعنی آرام\u200cتر.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='زمان هر خبر در نوار فوری (ثانیه)'),
        ),
    ]
