# Generated by Django 5.2.3 on 2026-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_sitesettings_ticker_hold_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViceUnitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='دقیقاً همان نامی که در منو دیده می\u200cشود، مثلاً «ادارهٔ امتحانات».', max_length=200, unique=True, verbose_name='نام واحد در چارت')),
                ('url', models.CharField(help_text='نشانی صفحه در همین سایت یا بیرون از آن.', max_length=300, verbose_name='نشانی مقصد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'لینک واحد معاونت',
                'verbose_name_plural': 'لینک واحدهای معاونت',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='viceunit',
            name='link',
            field=models.CharField(blank=True, help_text='اگر این واحد در سایت صفحه\u200cای دارد، نشانی\u200cاش را بنویسید تا در منو قابل کلیک شود.', max_length=300, verbose_name='نشانی صفحه'),
        ),
    ]
