# Generated by Django 5.2.3 on 2026-09-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_viceunitlink_viceunit_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='university_location_fa',
            field=models.CharField(blank=True, default='بابلسر-بهنمیر', max_length=100, verbose_name='زیرعنوان سربرگ (محل موسسه)'),
        ),
    ]
