# Generated by Django 5.2.3 on 2026-09-20 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_sitesettings_university_location_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='ticker_hold_seconds',
            field=models.PositiveSmallIntegerField(default=2, help_text='نوار این چند ثانیه خالی می\u200cماند و بعد خبر از سمت چپ وارد می\u200cشود. صفر یعنی بدون مکث. عدد فارسی هم پذیرفته می\u200cشود.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='مکث پیش از ورود خبر (ثانیه)'),
        ),
    ]
