# Generated by Django 5.2.3 on 2026-09-20 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_ticker_hold_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='ticker_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='هر اطلاعیه چند ثانیه طول بکشد تا از چپ به راست رد شود. عدد بزرگ\u200cتر یعنی آرام\u200cتر. عدد فارسی هم پذیرفته می\u200cشود.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='زمان هر خبر در نوار فوری (ثانیه)'),
        ),
    ]
