# Generated by Django 5.2.3 on 2026-09-20 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_ticker_speed_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='ticker_hold_seconds',
            field=models.PositiveSmallIntegerField(default=0, help_text='نوار این چند ثانیه خالی می\u200cماند و بعد خبر از سمت چپ وارد می\u200cشود. این زمان به «زمان هر خبر» اضافه می\u200cشود، از آن کم نمی\u200cکند. صفر یعنی بی\u200cوقفه.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='مکث پیش از ورود خبر (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ticker_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='هر اطلاعیه چند ثانیه طول بکشد تا از لبهٔ چپ صفحه تا لبهٔ راست برود. عدد بزرگ\u200cتر یعنی آرام\u200cتر — ۴۵ تا ۶۰ برای خواندن راحت است و زیر ۱۰ عملاً خوانده نمی\u200cشود.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='زمان هر خبر در نوار فوری (ثانیه)'),
        ),
    ]
