# Generated by Django 5.2.3 on 2026-09-20 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_ticker_no_pause_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='ticker_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='هر اطلاعیه چند ثانیه طول بکشد تا از لبهٔ چپ صفحه تا لبهٔ راست برود. عدد بزرگ\u200cتر یعنی آرام\u200cتر — ۴۵ تا ۶۰ برای خواندن راحت است و زیر ۱۰ عملاً خوانده نمی\u200cشود.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='سرعت نوار فوری — ثانیه برای یک عبور (بزرگ\u200cتر = آهسته\u200cتر)'),
        ),
    ]
