# Generated by Django 5.2.3 on 2026-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, unique=True, verbose_name='مقطع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('requirements', models.TextField(verbose_name='شرایط پذیرش')),
                ('tuition_info', models.TextField(blank=True, verbose_name='اطلاعات شهریه')),
                ('documents_required', models.TextField(blank=True, verbose_name='مدارک لازم')),
                ('registration_link', models.URLField(blank=True, verbose_name='لینک ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='مهلت ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'اطلاعات پذیرش',
                'verbose_name_plural': 'اطلاعات پذیرش',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(verbose_name='آدرس')),
                ('desired_major', models.CharField(max_length=200, verbose_name='رشته مورد علاقه')),
                ('degree', models.CharField(choices=[('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='مقطع')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل')),
                ('previous_degree', models.CharField(blank=True, max_length=200, verbose_name='مدرک قبلی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('waiting', 'لیست انتظار')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درخواست پذیرش',
                'verbose_name_plural': 'درخواست\u200cهای پذیرش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=200, verbose_name='رشته')),
                ('degree', models.CharField(max_length=50, verbose_name='مقطع')),
                ('base_fee', models.PositiveIntegerField(verbose_name='شهریه پایه (تومان)')),
                ('per_credit_fee', models.PositiveIntegerField(verbose_name='شهریه هر واحد (تومان)')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سال تحصیلی')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'شهریه',
                'verbose_name_plural': 'شهریه\u200cها',
            },
        ),
    ]
