# Generated by Django 5.2.3 on 2026-07-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'کد تأیید پذیرش',
                'verbose_name_plural': 'کدهای تأیید پذیرش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TuitionDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('grade', 'تخفیف رتبه/معدل ممتاز'), ('sibling', 'تخفیف خواهر و برادر'), ('cash', 'تخفیف پرداخت نقدی/زودهنگام'), ('talent', 'بورسیه استعداد درخشان'), ('prev_gpa', 'تخفیف/افزایش بر اساس معدل ترم قبل')], max_length=20, verbose_name='نوع تخفیف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='شرایط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تخفیف شهریه',
                'verbose_name_plural': 'تخفیف\u200cها و بورسیه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TuitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سال تحصیلی')),
                ('major', models.CharField(max_length=200, verbose_name='رشته')),
                ('degree', models.CharField(max_length=50, verbose_name='مقطع')),
                ('fixed_fee', models.PositiveBigIntegerField(default=0, verbose_name='شهریه ثابت')),
                ('theory_fee', models.PositiveBigIntegerField(default=0, verbose_name='هر واحد نظری')),
                ('practical_fee', models.PositiveBigIntegerField(default=0, verbose_name='هر واحد عملی')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'تاریخچه شهریه',
                'verbose_name_plural': 'تاریخچه شهریه\u200cها',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='previous_degree',
        ),
        migrations.AddField(
            model_name='admissioninfo',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='۰ = نامحدود', verbose_name='ظرفیت کل'),
        ),
        migrations.AddField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت کارشناس پذیرش'),
        ),
        migrations.AddField(
            model_name='application',
            name='agreed_terms',
            field=models.BooleanField(default=False, verbose_name='پذیرش قوانین'),
        ),
        migrations.AddField(
            model_name='application',
            name='desired_major2',
            field=models.CharField(blank=True, max_length=200, verbose_name='اولویت دوم رشته'),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_military',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/docs/', verbose_name='کارت پایان خدمت/معافیت'),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_national_id',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/docs/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/docs/', verbose_name='عکس پرسنلی'),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_prev_degree',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/docs/', verbose_name='تصویر مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='application',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مصاحبه'),
        ),
        migrations.AddField(
            model_name='application',
            name='know_from',
            field=models.CharField(choices=[('social', 'شبکه\u200cهای اجتماعی'), ('friend', 'معرفی دوست/آشنا'), ('site', 'وب\u200cسایت دانشگاه'), ('exhibition', 'نمایشگاه'), ('other', 'سایر')], default='site', max_length=20, verbose_name='نحوه آشنایی'),
        ),
        migrations.AddField(
            model_name='application',
            name='military',
            field=models.CharField(blank=True, choices=[('done', 'پایان خدمت'), ('exempt', 'معافیت'), ('student', 'معافیت تحصیلی'), ('na', 'مشمول نمی\u200cشود')], default='na', max_length=20, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_emergency',
            field=models.CharField(blank=True, max_length=15, verbose_name='تلفن اضطراری'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='موبایل تأیید شده'),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_degree',
            field=models.CharField(choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد')], default='diploma', max_length=20, verbose_name='آخرین مدرک'),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_grad_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='سال فارغ\u200cالتحصیلی'),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_major',
            field=models.CharField(blank=True, max_length=200, verbose_name='رشته مدرک قبلی'),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مدرسه/مرکز'),
        ),
        migrations.AddField(
            model_name='application',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد'),
        ),
        migrations.AddField(
            model_name='application',
            name='shift',
            field=models.CharField(choices=[('day', 'روزانه'), ('evening', 'شبانه'), ('both', 'هر دو')], default='day', max_length=10, verbose_name='ترجیح شیفت'),
        ),
        migrations.AddField(
            model_name='application',
            name='special_needs',
            field=models.TextField(blank=True, verbose_name='نیاز ویژه / شرایط خاص'),
        ),
        migrations.AddField(
            model_name='application',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(default='', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='application',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='application',
            name='desired_major',
            field=models.CharField(max_length=200, verbose_name='اولویت اول رشته'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('incomplete', 'نیاز به تکمیل مدارک'), ('interview', 'دعوت به مصاحبه'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('waiting', 'لیست انتظار')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveSmallIntegerField(default=1, verbose_name='شماره قسط')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (تومان)')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='فیش واریزی')),
                ('status', models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('pending', 'در انتظار تأیید'), ('overdue', 'معوق'), ('waived', 'بخشوده\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('confirmed_by', models.CharField(blank=True, max_length=100, verbose_name='تأیید توسط')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.application', verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'پرداخت دانشجو',
                'verbose_name_plural': 'پرداخت\u200cهای دانشجویان',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TuitionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=200, verbose_name='رشته')),
                ('degree', models.CharField(max_length=50, verbose_name='مقطع')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سال تحصیلی')),
                ('fixed_fee', models.PositiveBigIntegerField(default=0, verbose_name='شهریه ثابت (تومان)')),
                ('theory_fee', models.PositiveBigIntegerField(default=0, verbose_name='شهریه هر واحد نظری (تومان)')),
                ('practical_fee', models.PositiveBigIntegerField(default=0, verbose_name='شهریه هر واحد عملی (تومان)')),
                ('lab_fee', models.PositiveBigIntegerField(default=0, verbose_name='شهریه هر واحد عملی\u200cآزمایشگاهی (تومان)')),
                ('registration_fee', models.PositiveBigIntegerField(default=0, verbose_name='هزینه ثبت\u200cنام')),
                ('insurance_fee', models.PositiveBigIntegerField(default=0, verbose_name='بیمه دانشجویی')),
                ('card_fee', models.PositiveBigIntegerField(default=0, verbose_name='کارت دانشجویی')),
                ('dorm_fee', models.PositiveBigIntegerField(default=0, verbose_name='خوابگاه (ماهانه)')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ساختار شهریه',
                'verbose_name_plural': 'ساختار شهریه\u200cها',
                'ordering': ['-academic_year', 'major'],
                'unique_together': {('major', 'degree', 'academic_year')},
            },
        ),
    ]
