# Generated by Django 5.2.3 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_major_fk_and_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioninfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='admissionotp',
            name='code',
            field=models.CharField(max_length=6, verbose_name='کد تأیید'),
        ),
        migrations.AlterField(
            model_name='admissionotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='admissionotp',
            name='expires_at',
            field=models.DateTimeField(verbose_name='انقضا'),
        ),
        migrations.AlterField(
            model_name='admissionotp',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده\u200cشده'),
        ),
        migrations.AlterField(
            model_name='admissionotp',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره موبایل'),
        ),
    ]
