# Generated by Django 5.2.3 on 2026-07-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_sync_model_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='موبایل'),
        ),
    ]
