# Generated by Django 5.2.3 on 2026-07-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_photo_hijab_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='prev_degree',
            field=models.CharField(choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('discontinuous_bachelor', 'کارشناسی ناپیوسته'), ('master', 'کارشناسی ارشد')], default='diploma', max_length=50, verbose_name='آخرین مدرک'),
        ),
    ]
