# Generated by Django 5.2.3 on 2026-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_canonical_degrees'),
        ('admissions', '0010_canonical_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='academic_record_code',
            field=models.CharField(blank=True, default='', help_text='برای استعلام از سامانه سنجش', max_length=30, verbose_name='کد سوابق تحصیلی'),
        ),
        migrations.AddField(
            model_name='application',
            name='birth_cert_no',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='application',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='محل تولد'),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='application',
            name='diploma_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل کتبی دیپلم'),
        ),
        migrations.AddField(
            model_name='application',
            name='diploma_type',
            field=models.CharField(blank=True, choices=[('math', 'ریاضی و فیزیک'), ('science', 'علوم تجربی'), ('humanities', 'علوم انسانی'), ('technical', 'فنی و حرفه\u200cای'), ('vocational', 'کار و دانش'), ('islamic', 'علوم و معارف اسلامی'), ('other', 'سایر')], default='', max_length=20, verbose_name='نوع دیپلم'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='نام ولی / تماس اضطراری'),
        ),
        migrations.AddField(
            model_name='application',
            name='issue_place',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='محل صدور'),
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متأهل')], default='single', max_length=10, verbose_name='وضعیت تأهل'),
        ),
        migrations.AddField(
            model_name='application',
            name='province',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='application',
            name='quota',
            field=models.CharField(blank=True, choices=[('free', 'آزاد'), ('region1', 'منطقه ۱'), ('region2', 'منطقه ۲'), ('region3', 'منطقه ۳'), ('shahed', 'شاهد و ایثارگر'), ('disabled', 'معلولین'), ('staff', 'کارکنان موسسه')], default='free', help_text='مبنای قانونی پذیرش و تخفیف شهریه', max_length=20, verbose_name='سهمیه'),
        ),
        migrations.AlterField(
            model_name='application',
            name='national_id',
            field=models.CharField(db_index=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'degree'], name='admissions__status_d7fdd4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['phone'], name='admissions__phone_ffe665_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('national_id', ''), _negated=True)), fields=('national_id',), name='uniq_active_application_per_national_id'),
        ),
    ]
