# Generated by Django 5.2.3 on 2026-08-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_application_academic_record_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='موبایل')),
                ('payload', models.JSONField(default=dict, verbose_name='داده\u200cهای فرم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ذخیره')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس فرم پذیرش',
                'verbose_name_plural': 'پیش\u200cنویس\u200cهای فرم پذیرش',
                'ordering': ['-updated_at'],
            },
        ),
    ]
