# Generated by Django 5.2.3 on 2026-09-20 14:46

import core.private_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_applicationdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='doc_military',
            field=models.ImageField(blank=True, null=True, upload_to=core.private_media.private_upload_to('admissions/docs'), verbose_name='کارت پایان خدمت/معافیت'),
        ),
        migrations.AlterField(
            model_name='application',
            name='doc_national_id',
            field=models.ImageField(blank=True, null=True, upload_to=core.private_media.private_upload_to('admissions/docs'), verbose_name='تصویر کارت ملی'),
        ),
        migrations.AlterField(
            model_name='application',
            name='doc_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.private_media.private_upload_to('admissions/docs'), verbose_name='عکس پرسنلی'),
        ),
        migrations.AlterField(
            model_name='application',
            name='doc_prev_degree',
            field=models.ImageField(blank=True, null=True, upload_to=core.private_media.private_upload_to('admissions/docs'), verbose_name='تصویر مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=core.private_media.private_upload_to('payments'), verbose_name='فیش واریزی'),
        ),
    ]
